# This workflow runs every day. Then Push the svg file to output branch.

name: Snake Animation of Contribution

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate snake-anime.svg
        uses: Platane/snk@master
        with:
          github_user_name: royrustdev
          svg_out_path: dist/snake-anime.svg

      - run: git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
